# vi: ft=dockerfile
FROM resin/%%RESIN_MACHINE_NAME%%-python:3.7-stretch

ENV INITSYSTEM on
EXPOSE 80 443
WORKDIR /usr/src/app

RUN apt-get update -qq \
	&& apt-get install -qqy haproxy certbot \
	&& apt-get clean && rm -rf /var/lib/apt/lists/*

COPY config/services /etc/systemd/system
COPY config/haproxy.cfg /etc/haproxy/haproxy.cfg
COPY *.sh ./
RUN systemctl enable haproxy.service certbot-renew.timer

CMD ["./entry.sh"]
